version : '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/code
    working_dir: /code
    privileged: true
    restart: always
    networks:
      - app-network
    env_file:
      - .env
networks:
  app-network:
    driver: bridge